# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://www.example.com/"
languageCode = "en-AU"
title = "SAFS GSS"

# Metadata
[params]
  author = "Mark Scheuerell"
  description = "Panel moderator"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "SAFS Graduate Student Symposium"
  description = "Panel discussion on non-academic careers in environmental science"

# Navigation section
[params.nav]
  mission = "Background"
  services = "Services"
  team = "Panelists"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = false

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul>"

# Services section
[params.services]
  enable = false
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Panel"
  description = "This collection of panelists have diverse backgrounds and experiences in scientific research and communication."

  [[params.team.item]]
    name = "Dr. Neala Kendall"
    position = "Research Scientist, WA Dept Fish and Wildlife"
    description = "Dr. Kendall leads the Statewide Quantitative Synthesis and Reporting Unit at the Washington Department of Fisheries and Wildlife, a team of scientists working on a variety of projects related to salmonid conservation and recovery. She received her PhD in Aquatic & Fishery Sciences from the University of Washington."
    img = "images/neala.jpg"
    email = "#"
    telephone = "#"
    facebook = "#"
    twitter = "https://twitter.com/NealaKendall"
    instagram = "#"
    linkedin = "https://www.linkedin.com/in/neala-kendall-37056a20/"

  [[params.team.item]]
    name = "Dr. Melissa Poe"
    position = "Social Scientist, WA Sea Grant"
    description = "Dr. Poe leads the social science program at Washington Sea Grant, where she works to identify, define and incorporate measures of human well-being and cultural practices into marine planning and ecosystem-based management. She is involved in Washington Sea Grant and NOAA’s ocean acidification and climate change programs, studying how our changing seas might impact the social and cultural values of West Coast coastal and fishing communities. Melissa serves as a social science advisor to regional bodies such as the Puget Sound Partnership. Melissa advises and mentors undergraduate and graduate students who are interested in human—nature interactions and earning degrees in programs ranging from human geography, public health, anthropology to environmental studies. She received her PhD in Anthropology from the University of Washington."
    img = "images/melissa.jpg"
    email = "206-685-8209"
    telephone = "mpoe@uw.edu"
    facebook = ""
    twitter = "https://twitter.com/mpoetree"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/melissa-r-poe-033aaa2b/"

  [[params.team.item]]
    name = "Dr. Beth Sanderson"
    position = "Research Biologist, National Marine Fisheries Service"
    description = "Dr. Sanderson leads the Ecosystem Analysis Program at NOAA's Northwest Fisheries Science Center, where she oversees a variety of research projects related to threatened and endangered species, non-native species, and shellfish aquaculture. Beth received her PhD in Zoology from the University of Wisconsin."
    img = "images/beth.jpg"
    email = "beth.sanderson@noaa.gov"
    telephone = ""
    facebook = ""
    twitter = ""
    instagram = ""
    linkedin = "https://www.linkedin.com/in/beth-sanderson-90305a95/"

  [[params.team.item]]
    name = "Ms. Jennifer Scheuerell"
    position = "Owner, Sound Data Management"
    description = "Ms. Scheuerell is the owner of Sound Data Management (SDM), a small consulting company that designs, builds, and runs custom information systems for clients in science and engineering. SDM specializes in developing custom solutions for their clients using a wide range of software and hardware. She received her MS in Aquatic & Fishery Sciences from the University of Washington."
    img = "images/jennifer.jpg"
    email = "206-406-9455"
    telephone = "jennifer@sound-data.com"
    facebook = "#"
    twitter = "https://twitter.com/sound_data_"
    instagram = "#"
    linkedin = "https://www.linkedin.com/in/jennifer-scheuerell-45887021/"

  [[params.team.item]]
    name = "Dr. Amanda Stanley"
    position = "Executive Director, COMPASS"
    description = "In her role as Executive Director of COMPASS, Dr. Stanley provides leadership in mission, vision, and strategy. She supports their staff to excel as coaches, connectors, and conversation changers, as they work together to empower scientists to engage in the public discourse on the environment. Prior to joining COMPASS, Amanda was the Conservation Science Program Officer at Wilburforce Foundation, directing the foundation's efforts to provide science capacity to grantees and partners, empowering scientists to engage in management and policy, and ensuring that decisions are made with the best available science. She received her PhD in Zoology from the University of Washington."
    img = "images/amanda.jpg"
    email = ""
    telephone = ""
    facebook = ""
    twitter = "https://twitter.com/AmandaConsSci"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/amanda-stanley-64167211/"

  [[params.team.item]]
    name = "Dr. Jodie Toft"
    position = "Deputy Director, Puget Sound Restoration Fund"
    description = "Dr. Toft is the Deputy Director of the Puget Sound Restoration Fund, where she advances their science, expands partnerships, and builds support for their unique brand of in-water restoration. Prior to PSRF, Jodie worked at The Nature Conservancy and The Natural Capital Project. She received her PhD in Aquatic & Fishery Sciences from the University of Washington."
    img = "images/jodie.jpg"
    email = ""
    telephone = ""
    facebook = ""
    twitter = ""
    instagram = ""
    linkedin = "https://www.linkedin.com/in/jodie-toft-97503a80/"

  [[params.team.item]]
    name = "Dr. Sacha Vignieri"
    position = "Deputy Editor, Science"
    description = "Dr. Vignieri is a Deputy Editor at the prestigious journal <i>Science</i>... She received her PhD in Zoology from the University of Washington."
    img = "images/sacha.jpg"
    email = ""
    telephone = ""
    facebook = ""
    twitter = "https://twitter.com/svignieri"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/sachavignieri/"

  [[params.team.item]]
    name = "Dr. Mark Scheuerell"
    position = "Moderator"
    description = "Dr. Scheuerell is an associate professor in the School of Aquatic and Fishery Sciences. Mark’s research interests lie at the intersection of ecology and management. He is broadly interested in the roles of natural and anthropogenic drivers on freshwater and coastal ecosystems, and the services we derive from them. He received his PhD in Zoology from the University of Washington."
    img = "images/mark.jpg"
    email = "scheuerl@uw.edu"
    telephone = "206-543-5997"
    twitter = "https://twitter.com/mark_scheuerell"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/markscheuerell/"


# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2019 Mark Scheuerell <br> Based upon the Hugo Icon theme by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  #github = "#"
  #twitter = "#"
  #facebook = "#"
  #vine = "#"
  #linkedin = "#"
  #instagram = "#"
  
